### PR TITLE
Create .npmignore

### PR DESCRIPTION
**Pull request by balupton**
[x] Reduces package bundle size as unnecessary for production files are trimmed from the package.

[x] Fixes flow-type breaking on packages that have this package in `node_modules` due to the error:

```
$ flow .
node_modules/conventional-changelog-core/test/fixtures/_malformation.json:1
  1: 
     ^ Unexpected end of input


Found 1 error
```

### CODE REVIEW

**Comment by stevemao** [comment]
Thanks for the PR @balupton . Last time when I did research on things like this, people tend not to include `.npmignore` in the package since npm3 makes the whole `npm_modules` a lot smaller and maintenance cost is high (Forgetting changing things like this has bitten me). Also people usually whitelist the files using `files` in package.json if they really want to. I'm not exactly sure what's the best practice now?

> Fixes flow-type breaking on packages that have this package in node_modules due to the error:

test fixtures shouldn't be linted/checked anyways. Would it be better to blacklist it for flow since you can't be sure that all packages are "clean"?

**Comment by bcoe** [comment]
see: https://github.com/conventional-changelog/conventional-changelog/issues/165

**Comment by jamiebuilds** [comment]
Added `package.json#files` in https://github.com/conventional-changelog/conventional-changelog/pull/211

**Comment by stevemao** [comment]
I merged the PR since the vote seems to favour whitelisting files. However, if anyone could answer [my question above](https://github.com/conventional-changelog-archived-repos/conventional-changelog-core/pull/22#issuecomment-270778816) it would be appreciated. Cheers!

**Pull request closed without merging**
